services:
  web:
    build:
      context: ../       # root folder ihelpbd
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app         # live code updates reflect
    ports:
      - "0.0.0.0:8000:8000"