services:
  web:
    build:
      context: ../      # root folder (ihelpbd/) থেকে build হবে
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app        # local code changes container-এ reflect হবে
    ports:
      - "8000:8000"
